"""url model create

Revision ID: 12ea6821f32b
Revises: 
Create Date: 2024-03-11 17:35:00.808229

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '12ea6821f32b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'url_map',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('original', sa.String(), nullable=False),
        sa.Column('short', sa.String(length=16), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('short'),
    )
    op.create_index(
        op.f('ix_url_map_timestamp'), 'url_map', ['timestamp'], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_url_map_timestamp'), table_name='url_map')
    op.drop_table('url_map')
    # ### end Alembic commands ###
